# This is a workflow that automatically increments the project's version
name: Version increment

on:
  push:
    branches: [master]
    
env:
  GH_TOKEN: ${{ secrets.REPO_TOKEN }}

jobs:
  update-version:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    if: ${{contains(github.event.head_commit.message, 'fix:') || contains(github.event.head_commit.message, 'revert:') || contains(github.event.head_commit.message, 'feat:') || contains(github.event.head_commit.message, 'build:') || contains(github.event.head_commit.message, 'perf:') || contains(github.event.head_commit.message, '!')}}
    steps:
      - uses: actions/checkout@main
        with:
          token: ${{ env.GH_TOKEN }}

      - run: git config --global user.name 'GitHub Actions'
      - run: git config --global user.email '${{ secrets.USER_EMAIL }}'

      - name: 'condition 1'
        if: ${{contains(github.event.head_commit.message, 'fix:') || contains(github.event.head_commit.message, 'revert:')}}
        run: npm version patch -m '[v%s] increment PATCH version number'

      - name: 'condition 2'
        if: ${{contains(github.event.head_commit.message, 'feat:') || contains(github.event.head_commit.message, 'build:') || contains(github.event.head_commit.message, 'perf:')}}
        run: npm version minor -m '[v%s] increment MINOR version number'

      - name: 'condition 3'
        if: ${{contains(github.event.head_commit.message, '!')}}
        run: npm version major -m '[v%s] increment MAJOR version number'

      - run: git push
