# This is a workflow that automatically increments the project's version
name: Version increment

on:
  push:
    branches: [master]

jobs:
  update-version:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    if: ${{startsWith(github.event.commits.message, 'fix') || startsWith(github.event.commits.message, 'feat') || contains(github.event.commits.message, 'BREAKING CHANGE') || contains(github.event.commits.message, '!')}}
    steps:
      - uses: actions/checkout@main
        with:
          token: ${{ secrets.GITHUB_TOKEN}}

      - run: git config --global user.name 'GitHub Actions'
      - run: git config --global user.email '${{secrets.USER_EMAIL}}'

      - name: 'condition 1'
        if: ${{startsWith(github.event.commits.message, 'fix')}}
        run: npm version patch -m 'increment PATCH version to %s'

      - name: 'condition 2'
        if: ${{startsWith(github.event.commits.message, 'feat')}}
        run: npm version minor -m 'increment MINOR version to %s'

      - name: 'condition 3'
        if: ${{contains(github.event.commits.message, 'BREAKING CHANGE') || contains(github.event.commits.message, '!')}}
        run: npm version major -m 'increment MAJOR version to %s'

      - run: git push
